myopedlist/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from ..songs.views import *
from ..users.views import UserProfileUpdate

urlpatterns = [
    url(r'^(?P<slug>\d+)/entry_create/$',
        ListEntryCreateView.as_view(),
        name='entry_create'),

    url(r'^entry/(?P<pk>\d+)/update/$',
        ListEntryUpdateView.as_view(),
        name='entry_update'),

    url(r'^entry/(?P<pk>\d+)/delete/$',
        ListEntryDeleteView.as_view(),
        name='entry_delete'),

    url(r'^$', home, name='home'),
    url(r'^anime/(?P<slug>[-_\w]+)/$', SongListByAnimeView.as_view(), name='song_list_by_anime'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^user/', include('myopedlist.users.urls', namespace='users')),
    url(r'^oped/', include('myopedlist.songs.urls', namespace='songs')),
    url(r'^votes/', include('qhonuskan_votes.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^list/(?P<slug>[-_\w]+)/$', SongListByUserView.as_view(),
        name='song_list_by_user'),


    url(r'^(?P<slug>\d+)/review/$', SongReviewCreateView.as_view(),
        name='review_create'),
    url(r'^review/(?P<pk>\d+)/update/$', SongReviewUpdateView.as_view(),
        name='review_update'),
    url(r'^review/(?P<pk>\d+)/delete/$', SongReviewDeleteView.as_view(),
        name='review_delete'),


    url(r'^(?P<slug>\d+)/reviews/$', SongReviewBySongView.as_view(),
        name='song_review_by_song'),
    url(r'^(?P<slug>\d+)/$', SongDetailView.as_view(),
        name='song_detail'),

    url(r'^summernote/', include('django_summernote.urls')),
]

myopedlist/songs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from .views import * #ListEntryCreate, ListEntryUpdate, ListEntryDelete

urlpatterns = [

    url(r'^top/', TopSongsView.as_view(), name='top_songs'),

]

myopedlist/users/urls.py
from django.conf.urls import url

from .views import UserDetailView, UserReviewsView, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/reviews/$', UserReviewsView.as_view(),
        name='reviews'),
    url(r'^profile/edit/$', UserProfileUpdate.as_view(), name='profile_update'),
]

myopedlist/users/models.py
import os
import uuid
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django_countries.fields import CountryField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{0}.{1}'.format(uuid.uuid4(), ext)
    return os.path.join('avatars', filename)


class UserProfile(models.Model):
    GENDER_CHOICES = (('F', _('Female')), ('M', _('Male')))
    avatar = ProcessedImageField(upload_to=get_file_path,
                                 blank=True, null=True,
                                 processors=[ResizeToFit(265, 320)],
                                 format='JPEG',
                                 options={'quality': 90},
                                 verbose_name=_('Avatar'))
    user = models.OneToOneField(User)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1,
                              verbose_name=_('Gender'))
    country = CountryField()
    about = models.TextField(verbose_name=_('About'), blank=True, null=True)

    def save(self, *args, **kwargs):
        try:
            this = UserProfile.objects.get(id=self.id)
            if this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except:
            pass
        super(UserProfile, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'slug': self.user.username})

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

myopedlist/songs/forms.py
from django import forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from .models import *
from crispy_forms.layout import Submit, Reset
from crispy_forms.helper import FormHelper


class ListEntryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ListEntryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Save')))
        self.helper.add_input(Reset('list_entry_reset',
                                    _('Reset'), css_class='btn-default'))

    class Meta:
        model = ListEntry
        fields = ('score',)


class SongReviewForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SongReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = SongReview
        exclude = ('entry',)


class ListEntryChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):
        return obj.song.title

myopedlist/users/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django_summernote.widgets import SummernoteInplaceWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import UserProfile


class SignupForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, label=_('First name'))
    last_name = forms.CharField(max_length=30, label=_('Last name'))

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'gender', 'country']

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        profile = user.profile
        profile.gender = self.cleaned_data['gender']
        profile.country = self.cleaned_data['country']
        profile.save()
        user.save()
        #or 1st profile then user?


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile

        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Save')))

myopedlist/songs/views.py
from datetime import timedelta

from django.core.urlresolvers import reverse
from django.db.models import Count, Avg
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone, translation
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import ListEntryForm, SongReviewForm
from .models import ListEntry, SongReview, Song, User, Anime
from ..utilities.mixins import LoginRequiredMixin, PermissionMixin, EntryMixin
#from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


def home(request):
    last_month = timezone.now().date() - timedelta(days=30)
    popular_last_month = ListEntry.objects.filter(date_created__gt=last_month) \
                    .values('song_id', 'song__title', 'song__anime__title',
                            'song__thumb_url') \
                    .annotate(average=Avg('score'), count=Count('song_id'))[:5]
    reviews = SongReview.objects.order_by('-date_created')[:5]
    best_last_month = ListEntry.objects.filter(date_created__gt=last_month) \
                    .values('song_id', 'song__title', 'song__anime__title',
                            'song__thumb_url') \
                    .annotate(average=Avg('score')).order_by('-average')
    context = dict(popular_last_month=popular_last_month, reviews=reviews,
                   best_last_month=best_last_month)
    return render(request, 'index.html', context)


class SongDetailView(DetailView):
    model = Song
    template_name = 'songs/song_detail.html'
    slug_field = 'id'

#   def dispatch(self, request, *args, **kwargs):
 #       self.song = Song.objects.get(id=kwargs['slug'])
  #      return redirect('songs:song_detail', kwargs={'id': self.song.id})

    def get_object(self):
        from django.http import Http404
        try:
            return super(SongDetailView, self).get_object()
        except Http404:
            return redirect('home')
#            return Song.objects.get_or_create(self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super(SongDetailView, self).get_context_data(**kwargs)
        song = self.object
        reviews = SongReview.objects.filter(
            entry__song__id=song.id).order_by('-date_created')[:3]
        context.update(dict(reviews=reviews, detail_page=True))
        return context


class SongListByUserView(ListView):
    model = ListEntry
    template_name = 'songs/song_list_by_user.html'

    def get_queryset(self):
        self.user_profile = get_object_or_404(
            User, username=self.kwargs['slug'])
        return ListEntry.objects.filter(user=self.user_profile)

    def get_context_data(self, **kwargs):
        context = super(SongListByUserView, self).get_context_data(**kwargs)
        context['user_profile'] = self.user_profile
        lang_info = translation.get_language_info(translation.get_language())
        context['lang'] = lang_info.get('name')
        return context


class ListEntryCreateView(LoginRequiredMixin, CreateView):
    model = ListEntry
    form_class = ListEntryForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.song = Song.objects.get(id=kwargs['slug'])
        try:
            entry = ListEntry.objects.get(user=request.user,
                                          song_id=self.song.id)
            return redirect(reverse('entry_update', kwargs={'pk': entry.pk, }))
        except ListEntry.DoesNotExist:
            pass
        return super(ListEntryCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.song = self.song
        return super(ListEntryCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username})

    def get_context_data(self, **kwargs):
        context = super(ListEntryCreateView, self).get_context_data(**kwargs)
        context['song'] = self.song
        return context


class ListEntryUpdateView(PermissionMixin, UpdateView):
    model = ListEntry
    form_class = ListEntryForm

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username})


class ListEntryDeleteView(PermissionMixin, DeleteView):
    model = ListEntry

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username, })


class SongReviewCreateView(EntryMixin, CreateView):
    model = SongReview
    form_class = SongReviewForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            try:
                review = SongReview.objects.get(
                    entry__song__id=kwargs['slug'],
                    entry__user=request.user.id)
                return redirect(reverse('review_update',
                                        kwargs={'pk': review.pk}))
            except SongReview.DoesNotExist:
                self.song = Song.objects.get(id=kwargs.get('slug'))
        return super(SongReviewCreateView, self).dispatch(request,
                                                          *args, **kwargs)

    def form_valid(self, form):
        form.instance.entry = self.entry
        return super(SongReviewCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(SongReviewCreateView, self).get_context_data(**kwargs)
        context['song'] = self.song
        return context

    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'slug': self.request.user.username})


class SongReviewUpdateView(PermissionMixin, UpdateView):
    model = SongReview
    form_class = SongReviewForm

    def get_success_url(self):
        return reverse('users:reviews',
                       kwargs={'slug': self.request.user.username})


class SongReviewDeleteView(PermissionMixin, DeleteView):
    model = SongReview

    def get_success_url(self):
        return reverse('users:reviews',
                       kwargs={'slug': self.request.user.username})


class SongReviewBySongView(ListView):
    model = SongReview
    template_name = 'songs/song_detail.html'

    def get_queryset(self):
        self.song = get_object_or_404(Song, id=self.kwargs['slug'])
        return SongReview.objects.all().filter(entry__song_id=self.song.id)

    def get_context_data(self, **kwargs):
        context = super(SongReviewBySongView, self).get_context_data(**kwargs)
        context['object'] = self.song
        context['reviews_page'] = True
        return context


class SongListByAnimeView(ListView):
    model = Song
    template_name = 'songs/song_list_by_anime.html'
    paginate_by = 20

    def get_queryset(self):
        self.anime = get_object_or_404(Anime, id=self.kwargs['slug'])
        return Song.objects.all().filter(anime__id=self.anime.id)

    def get_context_data(self, **kwargs):
        context = super(SongListByAnimeView, self).get_context_data(**kwargs)
        context['anime'] = self.anime
        return context


class TopSongsView(ListView):
    model = ListEntry
    template_name = 'songs/top_songs.html'
    paginate_by = 15

    def get_queryset(self):
        q = ListEntry.objects.filter(score__isnull=False)

        return q.values('song__id', 'song__title', 'song__thumb_url') \
                .annotate(average=Avg('score'), count=Count('song_id')) \
                .order_by('-average')

    def get_context_data(self, **kwargs):
        context = super(TopSongsView, self).get_context_data(**kwargs)
        return context

myopedlist/users/views.py
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from social.apps.django_app.default.models import UserSocialAuth

from myopedlist.users.forms import UserProfileForm
from ..utilities.mixins import LoginRequiredMixin
from ..songs.models import SongReview, ListEntry, Song
from ..users.models import User, UserProfile


class UserDetailView(DetailView):
    model = User
    template_name = 'users/user_detail.html'
    slug_field = 'username'

    def get_context_data(self, section=None, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        reviews = SongReview.objects.filter(entry__user=self.object).order_by('-date_created')
        #recommendations -> PlayLists = SongRecomendation.objects_with_scores.filter(entry1__user=self.object).distinct().order_by('-date_created')
#        section = self.kwargs['section'] why this does not work?
        section = self.kwargs.get('section')
        if section == 'reviews':
            context['reviews_page'] = True
        else:
            context['detail_page'] = True
            reviews = reviews[:3]
            context['updates'] = ListEntry.objects.filter(user=self.object).order_by('-last_modified')[:3]
        context['reviews'] = reviews
        return context


class UserReviewsView(ListView):
    model = SongReview
    template_name = 'users/user_detail.html' #other that extends it

    def get_queryset(self):
        self.user_profile = get_object_or_404(User, username=self.kwargs['slug'])
        return self.model.objects.filter(entry__user=self.user_profile)

    def get_context_data(self, **kwargs):
        context = super(UserReviewsView, self).get_context_data(**kwargs)
        context['object'] = self.user_profile
        context['reviews'] = self.object_list
        context['reviews_page'] = True
        return context


class UserPlaylistView(ListView):
    pass


class UserProfileUpdate(LoginRequiredMixin, UpdateView):

    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/userprofile_form.html'

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdate, self).get_context_data(**kwargs)
        steam_account_exists = UserSocialAuth.objects.filter(
            provider='steam',
            user=self.request.user).exists()
        context['steam_account_exists'] = steam_account_exists
        return context

myopedlist/templates/base.html
{% load i18n compress qhonuskan_votes %} {% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My OPED List</title>

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    {% compress css %}
    <link rel="stylesheet" type="text/less" href="{% static 'less/styles.less' %}">{% endcompress %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/380cb78f450/integration/bootstrap/3/dataTables.bootstrap.css" />
    <noscript>
        <link type="text/css" href="{% static 'css/noscript.css' %}" rel="stylesheet" />
    </noscript>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'img/logo.png' %}" alt="My OPED List" />
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="">{% trans 'Songs' %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'songs:top_songs' %}">{% trans 'Best ranked' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'Recently added' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'Most popular' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'Top playlists' %}</a>
                            </li>
                        </ul>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="dropdown">
                    <a href="">My stuff <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'song_list_by_user' user.username %}">{% trans 'My OPED list' %} </a>
                            </li>
                            <li>
                                <a href="{% url 'users:reviews' user.username %}">{% trans 'My reviews' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'My recommendations' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'My playlists' %}</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="">{{ user.username }}  <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'users:detail' user.username %}">{% trans 'View profile' %}</a>
                            </li>
                            <li>
                                <a href="{% url 'users:profile_update' %}">{% trans 'Edit profile' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'View friends' %}</a>
                            </li>
                            <li>
                                <a href="#">{% trans 'Pending requests' %}</a>
                            </li>
                        </ul>
                    </li>
                        <li>
                        <a href="{% url 'account_logout' %}" class="#">{% trans 'Logout' %}</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'account_login' %}" class="btn-login">{% trans 'Login' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'account_signup' %}" class="btn-primary">{% trans 'Signup' %}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% comment %}
    <div class="search-bar-wrapper">
        <div class="container">
            <form class="navbar-form navbar-left pull-right" role="search" action="{% url 'search' %}" method="GET">
                <div class="input-group input-group-sm">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="search-type-title">
                            {% if search_type == 'users' %} {% trans 'Users' %} {% else %} {% trans 'Games' %} {% endif %}
                            <span class="caret"></span>
                        </button>
                        <select id="search-type-select" name="search_type" class="form-control">
                            <option value="games" {% if search_type != 'users' %}selected="true" {% endif %}>{% trans 'Games' %}</option>
                            <option value="users" {% if search_type == 'users' %}selected="true" {% endif %}>{% trans 'Users' %}</option>
                        </select>
                        <script>
                        $('#search-type-select').addClass('hidden');
                        </script>
                        <ul class="dropdown-menu" id="search-type-ul">
                            <li><a href="">{% trans 'Games' %}</a>
                            </li>
                            <li><a href="">{% trans 'Users' %}</a>
                            </li>
                        </ul>
                    </div>

                    <input id="search-box" class="form-control" type="text" name="q" placeholder="{% if not query %}{% trans 'Search&#8230;' %}{% endif %}" autocomplete="off" {% if query %}value="{{ query }}" {% endif %}>
                    <span class="input-group-btn">
                        <button class="btn btn-default btn" type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
{% endcomment %}
    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% block page_header %}{% endblock %}</h1>
            </div>
        </div>
        <!-- /.row -->

        {% block content %}{% endblock %}

    </div>
    <!-- /.container -->
</body>

myopedlist/templates/index.html
{% extends 'base.html' %} {% load i18n humanize%}
{% block page_header %}{% trans 'Recent activity' %}{% endblock page_header%}
{% block content %}

    <div class="row">

        <div class="col-md-4 col-sm-6 col-xs-12">
            <section>
                <h3 class="section-title">{% trans 'Popular songs this month' %}</h3>
                {% for s in popular_last_month %} {% url 'song_detail' s.song_id as song_url %}
                    <table class="table table-no-borders">
                        <tr>
                            <td class="col-md-3">
                                <a href="{{ song_url }}">
                                    <img class="img-responsive" src="{{ s.song__thumb_url }}">
                                </a>
                            </td>

                            <td class="col-md-9">
                                <p><a href="{{ song_url }}">{{ s.song__title }}</a></p>
                                <p class="text-muted">{% blocktrans with c=s.count plural=s.count|pluralize %}Added {{ c }} time{{ plural }} in the last 30 days{% endblocktrans %}</p>
                            </td>
                        </tr>
                    </table>
                {% empty %}
                    <p>{% trans 'No entries were added this month.' %}</p>
                {% endfor %}
            </section>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <section>
                <h3 class="section-title">{% trans 'Best ranked songs this month' %}</h3>
                {% for b in best_last_month %} {% url 'song_detail' b.entry.song_id as song_url %}
                    <table class="table table-no-borders">
                        <tr>
                            <td class="col-md-3">
                                <a href="{{ song_url }}">
                                    <img class="img-responsive" src="{{ b.song__thumb_url }}">
                                </a>
                            </td>

                            <td class="col-md-9">
                                <p><a href="{{ song_url }}">{{ b.song__title }}</a>
                                <p class="text-muted">{% blocktrans with avg=b.average %}Scored {{ avg }}{% endblocktrans %}</p>
                                </p>
                            </td>
                        </tr>
                    </table>
                {% empty %}
                    <p>{% trans 'No entries were added this month.' %}</p>
                {% endfor %}
        </div>
        <div class="col-md-4">
            <section>
                <h3 class="section-title">{% trans 'Latest reviews' %}</h3>
                {% for r in reviews %} {% url 'song_detail' r.entry.song_id as song_url %}
                    <table class="table table-no-borders">
                        <tr>
                            <td class="col-md-3">
                                <a href="{{ song_url }}">
                                    <img class="img-responsive" src="{{ r.entry.song.thumb_url }}">
                                </a>
                            </td>

                            <td class="col-md-9">
                                <p><a href="{{ song_url }}">{{ r.entry.song.title }}</a></p>
                                <p>By <a href="{% url 'users:detail' r.entry.user %}">{{ r.entry.user }}</a></p>
                                <p>Created {{ r.entry.date_created|naturaltime }}</p>
                                <p>Review: {{ r.text|truncatewords:15 }}</p>
                                <p><a href="{% url 'users:reviews' r.entry.user %}#{{ r.entry.song.title }}">Full</a></p>
                            </td>
                        </tr>
                    </table>
                {% empty %}
                    <p>{% trans 'No entries were added this month.' %}</p>
                {% endfor %}
            </section>
        </div>
    </div>
    <!-- /.row -->

{% endblock content%}