myopedlist/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from ..songs.views import *
from ..users.views import UserProfileUpdate

urlpatterns = [
    url(r'^(?P<slug>\d+)/entry_create/$',
        ListEntryCreateView.as_view(),
        name='entry_create'),

    url(r'^entry/(?P<pk>\d+)/update/$',
        ListEntryUpdateView.as_view(),
        name='entry_update'),

    url(r'^entry/(?P<pk>\d+)/delete/$',
        ListEntryDeleteView.as_view(),
        name='entry_delete'),

    url(r'^$', home, name='home'),
    url(r'^anime/(?P<slug>[-_\w]+)/$', SongListByAnimeView.as_view(), name='song_list_by_anime'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^user/', include('myopedlist.users.urls', namespace='users')),
    url(r'^oped/', include('myopedlist.songs.urls', namespace='songs')),
    url(r'^votes/', include('qhonuskan_votes.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^list/(?P<slug>[-_\w]+)/$', SongListByUserView.as_view(),
        name='song_list_by_user'),


    url(r'^(?P<slug>\d+)/review/$', SongReviewCreateView.as_view(),
        name='review_create'),
    url(r'^review/(?P<pk>\d+)/update/$', SongReviewUpdateView.as_view(),
        name='review_update'),
    url(r'^review/(?P<pk>\d+)/delete/$', SongReviewDeleteView.as_view(),
        name='review_delete'),


    url(r'^(?P<slug>\d+)/reviews/$', SongReviewBySongView.as_view(),
        name='song_review_by_song'),
    url(r'^(?P<slug>\d+)/$', SongDetailView.as_view(),
        name='song_detail'),

    url(r'^summernote/', include('django_summernote.urls')),
]

myopedlist/songs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from .views import * #ListEntryCreate, ListEntryUpdate, ListEntryDelete

urlpatterns = [

    url(r'^top/', TopSongsView.as_view(), name='top_songs'),

]

myopedlist/users/urls.py
from django.conf.urls import url

from .views import UserDetailView, UserReviewsView, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/reviews/$', UserReviewsView.as_view(),
        name='reviews'),
    url(r'^profile/edit/$', UserProfileUpdate.as_view(), name='profile_update'),
]

myopedlist/songs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from qhonuskan_votes.models import (VotesField, ObjectsWithScoresManager,
                                    SortByScoresManager)


class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Anime(models.Model):
    title = models.CharField(max_length=200, unique=True)
    myanimelist_id = models.PositiveIntegerField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.title


class Song(models.Model):
    title = models.CharField(max_length=200)
    #No data  genre = models.ManyToManyField(Genre, null=True, blank=True)
    thumb_url = models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png')
    overview = models.TextField(null=True, blank=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    anime = models.ManyToManyField(Anime, related_name='oped_anime')
    OPED_CHOICES = (('OP', _('Opening')), ('ED', _('Ending')))
    oped = models.CharField(max_length=2, choices=OPED_CHOICES,
                            verbose_name=_('OP/ED'))
    number = models.PositiveSmallIntegerField(null=True, blank=True)
    #custom field (from-to episode, or nothing, which means all episodes)

    class Meta:
        unique_together = ('title', 'artist')

    def __str__(self):
        return self.title


class ListEntry(models.Model):
    SCORE_CHOICES = (
        (10, _('(10) Masterpiece')),
        (9, _('(9) Great')),
        (8, _('(8) Very good')),
        (7, _('(7) Good')),
        (6, _('(6) Fine')),
        (5, _('(5) Average')),
        (4, _('(4) Bad')),
        (3, _('(3) Very bad')),
        (2, _('(2) Horrible')),
        (1, _('(1) Appalling')),
    )
    user = models.ForeignKey(User)
    song = models.ForeignKey(Song)
    FAVORED_CHOICES = (
        (True, '❤'), (False, '-'),
    )
    favored = models.NullBooleanField(_('Favored'),
                                      choices=FAVORED_CHOICES,
                                      blank=True)
    score = models.PositiveSmallIntegerField(_('Score'),
                                             choices=SCORE_CHOICES,
                                             null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'list entries'
        unique_together = ('user', 'song')

    def __str__(self):
        return "{0}'s entry for {1}".format(self.user.username,
                                            self.song_id)


class SongReview(models.Model):
    entry = models.OneToOneField(ListEntry)
    text = models.TextField(_('Text'))
    date_created = models.DateTimeField(auto_now_add=True)
    votes = VotesField()
    objects = models.Manager()
    objects_with_scores = ObjectsWithScoresManager()
    sort_by_score = SortByScoresManager()

    def __str__(self):
        return "{0}'s review for {1}".format(self.entry.user.username,
                                             self.entry.song_id)

"""
class SongRecommendation(models.Model):
    entry1 = models.ForeignKey(ListEntry, related_name='recommendation_entry1')
    entry2 = models.ForeignKey(ListEntry, related_name='recommendation_entry2')
    text = models.TextField(_('Text'))
    date_created = models.DateTimeField(auto_now_add=True)
    votes = VotesField()
    objects = models.Manager()
    objects_with_scores = ObjectsWithScoresManager()
    sort_by_score = SortByScoresManager()

    class Meta:
        unique_together = ('entry1', 'entry2')

    def __str__(self):
        return "{0}'s recommendation for {1} - {2}".format(
            self.entry1.user.username,
            self.entry1.song_id,
            self.entry2.song_id)

    def save(self, *args, **kwargs):
        if self.entry1.song_id > self.entry2.song_id:
            self.entry1, self.entry2 = self.entry2, self.entry1
        super(SongRecommendation, self).save(*args, **kwargs)
"""

myopedlist/songs/views.py
from datetime import timedelta

from django.core.urlresolvers import reverse
from django.db.models import Count, Avg
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone, translation
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import ListEntryForm, SongReviewForm
from .models import ListEntry, SongReview, Song, User, Anime
from ..utilities.mixins import LoginRequiredMixin, PermissionMixin, EntryMixin
#from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


def home(request):
    last_month = timezone.now().date() - timedelta(days=30)
    popular_last_month = ListEntry.objects.filter(date_created__gt=last_month) \
                    .values('song_id', 'song__title', 'song__anime__title',
                            'song__thumb_url') \
                    .annotate(average=Avg('score'), count=Count('song_id'))[:5]
    reviews = SongReview.objects.order_by('-date_created')[:5]
    best_last_month = ListEntry.objects.filter(date_created__gt=last_month) \
                    .values('song_id', 'song__title', 'song__anime__title',
                            'song__thumb_url') \
                    .annotate(average=Avg('score')).order_by('-average')
    context = dict(popular_last_month=popular_last_month, reviews=reviews,
                   best_last_month=best_last_month)
    return render(request, 'index.html', context)


class SongDetailView(DetailView):
    model = Song
    template_name = 'songs/song_detail.html'
    slug_field = 'id'

#   def dispatch(self, request, *args, **kwargs):
 #       self.song = Song.objects.get(id=kwargs['slug'])
  #      return redirect('songs:song_detail', kwargs={'id': self.song.id})

    def get_object(self):
        from django.http import Http404
        try:
            return super(SongDetailView, self).get_object()
        except Http404:
            return redirect('home')
#            return Song.objects.get_or_create(self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super(SongDetailView, self).get_context_data(**kwargs)
        song = self.object
        reviews = SongReview.objects.filter(
            entry__song__id=song.id).order_by('-date_created')[:3]
        context.update(dict(reviews=reviews, detail_page=True))
        return context


class SongListByUserView(ListView):
    model = ListEntry
    template_name = 'songs/song_list_by_user.html'

    def get_queryset(self):
        self.user_profile = get_object_or_404(
            User, username=self.kwargs['slug'])
        return ListEntry.objects.filter(user=self.user_profile)

    def get_context_data(self, **kwargs):
        context = super(SongListByUserView, self).get_context_data(**kwargs)
        context['user_profile'] = self.user_profile
        lang_info = translation.get_language_info(translation.get_language())
        context['lang'] = lang_info.get('name')
        return context


class ListEntryCreateView(LoginRequiredMixin, CreateView):
    model = ListEntry
    form_class = ListEntryForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.song = Song.objects.get(id=kwargs['slug'])
        try:
            entry = ListEntry.objects.get(user=request.user,
                                          song_id=self.song.id)
            return redirect(reverse('entry_update', kwargs={'pk': entry.pk, }))
        except ListEntry.DoesNotExist:
            pass
        return super(ListEntryCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.song = self.song
        return super(ListEntryCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username})

    def get_context_data(self, **kwargs):
        context = super(ListEntryCreateView, self).get_context_data(**kwargs)
        context['song'] = self.song
        return context


class ListEntryUpdateView(PermissionMixin, UpdateView):
    model = ListEntry
    form_class = ListEntryForm

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username})


class ListEntryDeleteView(PermissionMixin, DeleteView):
    model = ListEntry

    def get_success_url(self):
        return reverse('song_list_by_user',
                       kwargs={'slug': self.request.user.username, })


class SongReviewCreateView(EntryMixin, CreateView):
    model = SongReview
    form_class = SongReviewForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            try:
                review = SongReview.objects.get(
                    entry__song__id=kwargs['slug'],
                    entry__user=request.user.id)
                return redirect(reverse('review_update',
                                        kwargs={'pk': review.pk}))
            except SongReview.DoesNotExist:
                self.song = Song.objects.get(id=kwargs.get('slug'))
        return super(SongReviewCreateView, self).dispatch(request,
                                                          *args, **kwargs)

    def form_valid(self, form):
        form.instance.entry = self.entry
        return super(SongReviewCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(SongReviewCreateView, self).get_context_data(**kwargs)
        context['song'] = self.song
        return context

    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'slug': self.request.user.username})


class SongReviewUpdateView(PermissionMixin, UpdateView):
    model = SongReview
    form_class = SongReviewForm

    def get_success_url(self):
        return reverse('users:reviews',
                       kwargs={'slug': self.request.user.username})


class SongReviewDeleteView(PermissionMixin, DeleteView):
    model = SongReview

    def get_success_url(self):
        return reverse('users:reviews',
                       kwargs={'slug': self.request.user.username})


class SongReviewBySongView(ListView):
    model = SongReview
    template_name = 'songs/song_detail.html'

    def get_queryset(self):
        self.song = get_object_or_404(Song, id=self.kwargs['slug'])
        return SongReview.objects.all().filter(entry__song_id=self.song.id)

    def get_context_data(self, **kwargs):
        context = super(SongReviewBySongView, self).get_context_data(**kwargs)
        context['object'] = self.song
        context['reviews_page'] = True
        return context


class SongListByAnimeView(ListView):
    model = Song
    template_name = 'songs/song_list_by_anime.html'
    paginate_by = 20

    def get_queryset(self):
        self.anime = get_object_or_404(Anime, id=self.kwargs['slug'])
        return Song.objects.all().filter(anime__id=self.anime.id)

    def get_context_data(self, **kwargs):
        context = super(SongListByAnimeView, self).get_context_data(**kwargs)
        context['anime'] = self.anime
        return context


class TopSongsView(ListView):
    model = ListEntry
    template_name = 'songs/top_songs.html'
    paginate_by = 15

    def get_queryset(self):
        q = ListEntry.objects.filter(score__isnull=False)

        return q.values('song__id', 'song__title', 'song__thumb_url') \
                .annotate(average=Avg('score'), count=Count('song_id')) \
                .order_by('-average')

    def get_context_data(self, **kwargs):
        context = super(TopSongsView, self).get_context_data(**kwargs)
        return context

myopedlist/users/views.py
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from social.apps.django_app.default.models import UserSocialAuth

from myopedlist.users.forms import UserProfileForm
from ..utilities.mixins import LoginRequiredMixin
from ..songs.models import SongReview, ListEntry, Song
from ..users.models import User, UserProfile


class UserDetailView(DetailView):
    model = User
    template_name = 'users/user_detail.html'
    slug_field = 'username'

    def get_context_data(self, section=None, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        reviews = SongReview.objects.filter(entry__user=self.object).order_by('-date_created')
        #recommendations -> PlayLists = SongRecomendation.objects_with_scores.filter(entry1__user=self.object).distinct().order_by('-date_created')
#        section = self.kwargs['section'] why this does not work?
        section = self.kwargs.get('section')
        if section == 'reviews':
            context['reviews_page'] = True
        else:
            context['detail_page'] = True
            reviews = reviews[:3]
            context['updates'] = ListEntry.objects.filter(user=self.object).order_by('-last_modified')[:3]
        context['reviews'] = reviews
        return context


class UserReviewsView(ListView):
    model = SongReview
    template_name = 'users/user_detail.html' #other that extends it

    def get_queryset(self):
        self.user_profile = get_object_or_404(User, username=self.kwargs['slug'])
        return self.model.objects.filter(entry__user=self.user_profile)

    def get_context_data(self, **kwargs):
        context = super(UserReviewsView, self).get_context_data(**kwargs)
        context['object'] = self.user_profile
        context['reviews'] = self.object_list
        context['reviews_page'] = True
        return context


class UserPlaylistView(ListView):
    pass


class UserProfileUpdate(LoginRequiredMixin, UpdateView):

    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/userprofile_form.html'

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdate, self).get_context_data(**kwargs)
        steam_account_exists = UserSocialAuth.objects.filter(
            provider='steam',
            user=self.request.user).exists()
        context['steam_account_exists'] = steam_account_exists
        return context

myopedlist/templates/songs/_review_layout.html
{% load i18n staticfiles user_tags %} {% url 'home' as home_url %}
{% with user_profile=obj.entry.user entry=obj.entry %}
    <section>
        <table class="table table-no-borders">
            <tr>
                {% block table_content %}
                {% endblock table_content %}

                <td class="text-right col-md-6">
                    <p>
                        {% blocktrans with score=obj.entry.score %} Given score: {{ score }} {% endblocktrans %}
                    </p>
                </td>
            </tr>
        </table>
        {{ obj.text|linebreaks }}
        {% if request.user == obj.entry.user %}
        <div class="text-right">
            <a href="{% url 'review_update' obj.pk %}" class="btn btn-default btn-xs">{% trans 'Edit' %}</a>
            <a href="{% url 'review_delete' obj.pk %}" class="btn btn-default btn-xs">{% trans 'Delete' %}</a>
        </div>
        {% endif %}
        {% if not forloop.last %}
            <hr />
        {% endif %}
    </section>
{% endwith %}

myopedlist/templates/songs/_song_review_layout.html
{% extends 'songs/_review_layout.html' %}
{% load i18n user_tags %}
{% block table_content %}
    <td class="col-md-1">
        <a href="{% url 'users:detail' user_profile.username %}">
            <img class="img-responsive" src="{% avatar_or_default user_profile %}">
        </a>
    </td>

    <td class="col-md-5">
        <p>{% trans 'By' %} <a href="{% url 'users:detail' user_profile.username %}">{{ user_profile.username }}</a>
        </p>
        <p><a href="{% url 'users:reviews' user_profile.username %}">{% trans 'View other reviews by this user' %}</a>
        </p>
    </td>
{% endblock %}

myopedlist/templates/songs/_user_entry_layout.html
{% load i18n %} {% load i18n qhonuskan_votes staticfiles user_tags %} {% url 'home' as home_url %}
{% with user_profile=obj.entry.user %}
    <section>
        <table class="table table-no-borders">
            <tr>
                <td class="col-md-1">
                    <a href="{% url 'song_detail' obj.song.id %}">
                        <img class="img-responsive"
                             src="{% if obj.song.thumb_url %}{{ obj.song.thumb_url }}{% endif %}">
                    </a>
                </td>
                <td class="col-md-5">
                    <p>
                        <a href="{% url 'song_detail' obj.song.id %}">{{ obj.song.title }}</a>
                    </p>
                </td>

                <td class="text-right col-md-6">

                    <p>
                        {% blocktrans with score=obj.score %} Given score: {{ score }} {% endblocktrans %}
                    </p>
                </td>
            </tr>
        </table>
        {{ obj.text|linebreaks }}
        {% if user_profile == user %}
            <div class="text-right">
                <a href="{% url 'entry_update' obj.pk %}" class="btn btn-default btn-xs">{% trans 'Edit' %}</a>
                <a href="{% url 'entry_delete' obj.pk %}" class="btn btn-default btn-xs">{% trans 'Delete' %}</a>
            </div>
        {% endif %} {% if not forloop.last %}
        <hr/>{% endif %}
    </section>
{% endwith %}

myopedlist/templates/songs/_user_review_layout.html
{% extends 'songs/_review_layout.html' %}
{% load i18n %}
{% block table_content %}
    <td class="col-md-1">
        <a href="{% url 'song_detail' entry.song.id %}">
            <img class="img-responsive" src="{% if entry.song.thumb_url %}{{ entry.song.thumb_url }}{% endif %}">
        </a>
    </td>
    <td class="col-md-5">
        <p><a name="{{ entry.song.title }}" href="{% url 'song_detail' entry.song.id %}">{{ entry.song.title }}</a>
        </p>
        {% if request.get_full_path == home_url %}
            <p>{% trans 'By' %} <a href="{% url 'users:detail' user_profile.username %}">{{ user_profile.username }}</a>
            </p>
        {% else %}
            <p><a href="{% url 'song_review_by_song' entry.song.id %}">{% trans 'View other reviews for this song' %}</a>
            </p>
        {% endif %}
    </td>
{% endblock %}

myopedlist/templates/songs/listentry_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block page_header %}{% trans 'Remove song from list' %}{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

            <form action="" method="POST">{% csrf_token %}
                <p>{% trans 'Are you sure you want to remove this song from your list?' %}</p>
                <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}" />
                <a href="" class="btn btn-default" id="cancel">{% trans 'Cancel' %}</a>
            </form>
        </div>

        <script type="text/javascript">
            $('#cancel').click(function (e) {
                e.preventDefault();
                history.back();
            });
        </script>
    </div>

{% endblock %}

myopedlist/templates/songs/listentry_form.html
{% extends 'base.html' %}
{% load i18n crispy_forms_tags %}

{% block page_header %}
    {% if not form.instance.pk %}
        {% blocktrans with song_title=song.title %}
            Add {{ song_title }} to my list
        {% endblocktrans %}
    {% else %}
        {% blocktrans with song_title=form.instance.song.title %}
            Edit {{ song_title }} in my list
        {% endblocktrans %}
    {% endif %}
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% crispy form %}
                </div>
            </div>
        </div>

    </div>
    <!-- /.row -->

{% endblock %}

myopedlist/templates/songs/song_list_by_anime.html
{% extends 'base.html' %} {% load i18n imagekit %} {% load static from staticfiles %}

{% block page_header %}

    {% blocktrans with title=anime.title %}
        {{ title }}'s OPED list
    {% endblocktrans %}

{% endblock page_header %}

<style>
img {
    max-width: 100%;
    max-height: 100%;
}
    .square {
        height: 75px;
        width: 75px;
    }
</style>

{% block content %}

    {% for s in object_list %}
    {% url 'song_detail' s.id as song_url %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <a href="{{ song_url }}">
                    <link rel="stylesheet" type="text/css" href="{% static 'css/oped_img.css'%}">
                    <img class="oped-img" src="{{ s.thumb_url }}"/>
                </a>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <p><a href="{{ song_url }}">{{ s.title }}</a></p>
                <p>{{ s.oped }} {{ s.number|default_if_none:"-" }}</p>
            </div>
            </div>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <div class="row">
            <div class="col-md-12">
                <ul class="pagination pagination-centered">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page=1">
                                &laquo;</a>
                        </li>
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}">
                                &lt;</a>
                        </li>
                    {% endif %} {% for i in paginator.page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endfor %} {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                    </li>
                    <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

myopedlist/templates/songs/song_list_by_user.html
{% extends 'base.html' %} {% load i18n %} {% load static from staticfiles %}

{% block page_header %}

    {% blocktrans with username=user_profile.username %}
        {{ username }}'s songs list
    {% endblocktrans %}

{% endblock page_header %}

{% block content %} {% regroup object_list|dictsortreversed:"score" by get_score_display as score_list %}

    <div class="row">

        {% if score_list %}
            <div class="col-md-12 text-left">
            <link rel="stylesheet" type="text/css" href="{% static 'css/force_scrollbar.css'%}">
            <div class="btn-group text-center" id="catpicker">
                <div class="btn-group dropup" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter by score <span class="caret"></span>
                </button>
                    <link rel="stylesheet" type="text/css" href="{% static 'css/horizontal_scores.css'%}">
                    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <script src="{% static 'js/filter.js' %}"></script>
                        <a href="#" id="allcat" class="current btn btn-primary" disabled="disabled">{% trans 'No filter' %}</a>
                        {% for e in score_list %}
                            <a href="#" id="{{ e.grouper|slugify }}" class="filter btn btn-primary">{{ e.grouper }}</a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            </div>
        {% endif %}

        <div class="col-md-12">

            {% for e in score_list %}
                <section class="discounted-item {{ e.grouper|slugify }}">
                    <h3 class="section-title">{{ e.grouper }}</h3>
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="col-md-5">{% trans 'Song title' %}</th>
                            <th class="col-md-1">{% trans 'Favored' %}</th>
                            <th class="col-md-3">{% trans 'From anime(s)' %}</th>
                            <th class="col-md-1">{% trans 'Type' %}</th>
                            <th class="col-md-1">{% trans '#' %}</th>
                            <th class="col-md-3">{% trans 'Artist' %}</th>
                            {% if user_profile == user %}
                                <th class="col-md-2"></th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for entry in e.list %}
                            <tr>
                                <td>
                                    <a href="{% url 'song_detail' entry.song.id %}">{{ entry.song.title }}</a>
                                </td>
                                <td>
                                    {{ entry.get_favored_display|default_if_none:"-" }}
                                </td>
                                <td>
                                    {% for anime in entry.song.anime.all %}
                                        <a href="{% url 'song_list_by_anime' anime.id %}">{{ anime.title }}</a>
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {{ entry.song.oped }}
                                </td>
                                <td>
                                    {{ entry.song.number|default_if_none:"-" }}
                                </td>
                                <td>
                                    {{ entry.song.artist }}
                                </td>
                                {% comment %}<td>
                                    {{ entry.score|default_if_none:"" }}
                                </td>
                                {% endcomment %}
                                {% if user_profile == user %}
                                    <td class="text-right">
                                        <a href="{% url 'entry_update' entry.id %}" class="btn btn-default btn-xs">{% trans 'Edit' %}</a>
                                        <a href="{% url 'entry_delete' entry.id %}" class="btn btn-default btn-xs">{% trans 'Remove' %}</a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </section>
            {% empty %}
                <p>{% trans "This user hasn't added any songs to its list yet." %}</p>
            {% endfor %}

        </div>

    </div>
    <!-- /.row -->

{% endblock %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/filter.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.3/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/plug-ins/380cb78f450/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.table').DataTable({% if lang != 'English' %}{
                "language": {
                    {% with 'json/dataTables_'|add:lang|add:'.json' as lang_file %}
                        "url": "{% static lang_file %}"
                    {% endwith %}
                }
                }{% endif %});
        });
    </script>
{% endblock %}